[package]
name = "timevec"
version = "0.2.0"
edition = "2021"
authors = ["Rostyslav Bohomaz <rostyslav.db@gmail.com>"]
license = "MIT"
description = "Time limited vector deque"
repository = "https://github.com/rostyq/timevec"
